### ISSUE TITLE
感觉挺不错的，可以用在生产环境吗？

### ISSUE THREAD

**Issue by springleng** [TIGERB/naruto#2]

**Comment by TIGERB** [comment]
完全可以啊～ 哈哈～

**Comment by springleng** [comment]
PHP7.1、7.2下报：
PHP Notice:  A non well formed numeric value encountered in /vagrant_data/caipiao_api/naruto/src/Daemon.php on line 54

**Comment by TIGERB** [comment]
忘了说了 目前只在ubuntu&mac测试过  别的系统没测过，代码 是下面这样么？
```
public function check(Manager $manager)
	{
		if (! empty($manager->waitSignalProcessPool['signal'])) {
            return;
        }

        // get num now
		$num = shell_exec("pstree -p {$manager->master->pid} | grep php | wc -l") - 3;
		
        // check num
        $diff = $manager->startNum - $num;
        if ($diff > 0) {
            // start worker
            $manager->execFork($diff);   
        }
	}
```

**Comment by TIGERB** [comment]
那块代码挺简单的 就是获取当前子进程的数量的shell 你可以debug下

**Comment by springleng** [comment]
类型转换一下就行了  $num = intval(shell_exec("pstree -p {$manager->master->pid} | grep php | wc -l")) - 3;

**Comment by TIGERB** [comment]
哦哦，欢迎pr, thx~

不过奇了怪了，不是弱类型么,难道 
```
shell_exec("pstree -p {$manager->master->pid} | grep php | wc -l")
```
的结果是个非数字的字符串～

wc -l 应该是个数字啊～

**Comment by springleng** [comment]
PHP 7 慢慢的再往强类型靠

**Comment by TIGERB** [comment]
可以把你那边

```
shell_exec("pstree -p {$manager->master->pid} | grep php | wc -l")
```
的结果打印发我么  我看看～

thx~

**Comment by springleng** [comment]
![qq 20180116173304](https://user-images.githubusercontent.com/1900972/34981730-59e00bc0-fae3-11e7-9d9e-aa41afdce327.png)

应该是多出了一个换行符了，你不说我还真以为是类型的问题

**Comment by springleng** [comment]
而且还发现一个问题  --worker-num=1的时候  pa aux | grep php  查看是5个进程

**Comment by TIGERB** [comment]
嗯，换行符～

bug欢迎提交 pull request，哈哈～

**Comment by TIGERB** [comment]
[而且还发现一个问题 --worker-num=1的时候 pa aux | grep php 查看是5个进程]

已经fix了～

thx~
