### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [TIGERB/naruto#7]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by TIGERB** [comment]
not active.

**Comment by ghost** [comment]
Hi TIGERB.

> not active.

thank you for feedback. I will close this issue, you clarified my doubt.

*Have a great day, and thank you for your patience in answering my question.*

***Note: I would like to help this open project. Is there anything I can do to help: naruto?***
